# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/bram/bram.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bram || ORIG_REF_NAME==bram} -quiet] -quiet

# IP: bd/bram/ip/bram_blk_mem_gen_0_0/bram_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bram_blk_mem_gen_0_0 || ORIG_REF_NAME==bram_blk_mem_gen_0_0} -quiet] -quiet

# XDC: /home/eelfire/iitgn/2_i/ES203/project/id-8/Cache-Controller-FPGA/Cache-Controller-FPGA.gen/sources_1/bd/bram/bram_ooc.xdc
