set_property PACKAGE_PIN J15 [get_ports reset]
set_property PACKAGE_PIN L16 [get_ports halt_in]
set_property PACKAGE_PIN J17 [get_ports {digit_en[0]}]
set_property PACKAGE_PIN J18 [get_ports {digit_en[1]}]
set_property PACKAGE_PIN T9 [get_ports {digit_en[2]}]
set_property PACKAGE_PIN J14 [get_ports {digit_en[3]}]
set_property PACKAGE_PIN T10 [get_ports {segments[0]}]
set_property PACKAGE_PIN R10 [get_ports {segments[1]}]
set_property PACKAGE_PIN K16 [get_ports {segments[2]}]
set_property PACKAGE_PIN K13 [get_ports {segments[3]}]
set_property PACKAGE_PIN P15 [get_ports {segments[4]}]
set_property PACKAGE_PIN T11 [get_ports {segments[5]}]
set_property PACKAGE_PIN L18 [get_ports {segments[6]}]
set_property PACKAGE_PIN H15 [get_ports {segments[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {digit_en[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit_en[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit_en[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit_en[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports halt_in]
set_property IOSTANDARD LVCMOS33 [get_ports reset]

set_property IOSTANDARD LVCMOS33 [get_ports {leds[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[0]}]
set_property PACKAGE_PIN H17 [get_ports {leds[0]}]
set_property PACKAGE_PIN K15 [get_ports {leds[1]}]
set_property PACKAGE_PIN J13 [get_ports {leds[2]}]
set_property PACKAGE_PIN N14 [get_ports {leds[3]}]
set_property PACKAGE_PIN R18 [get_ports {leds[4]}]
set_property PACKAGE_PIN V17 [get_ports {leds[5]}]
set_property PACKAGE_PIN U17 [get_ports {leds[6]}]
set_property PACKAGE_PIN U16 [get_ports {leds[7]}]
set_property PACKAGE_PIN V16 [get_ports {leds[8]}]
set_property PACKAGE_PIN T15 [get_ports {leds[9]}]
set_property PACKAGE_PIN U14 [get_ports {leds[10]}]
set_property PACKAGE_PIN T16 [get_ports {leds[11]}]
set_property PACKAGE_PIN V15 [get_ports {leds[12]}]
set_property PACKAGE_PIN V14 [get_ports {leds[13]}]
set_property PACKAGE_PIN V12 [get_ports {leds[14]}]
set_property PACKAGE_PIN V11 [get_ports {leds[15]}]




set_property PACKAGE_PIN E3 [get_ports clk_in]
set_property IOSTANDARD LVCMOS33 [get_ports clk_in]

create_clock -period 10.000 -name clk_in -waveform {0.000 5.000} [get_ports clk_in]